Css brochure form
bugass/c-0823-code-solutions pull request #33
Opened 2023-09-08 01:35 UTC by bugass

completed.

<img width="460" alt="Screenshot 2023-09-07 at 6 34 19 PM" src="https://github.com/bugass/c-0823-code-solutions/assets/102183396/d0bd7ccf-3c45-466b-93f2-5c4ff639a06a">

2023-09-08 16:24 UTC, shawnkost requested changes
Few changes here!

2023-09-08 16:24 UTC, shawnkost commented on css-brochure-form/index.html
> +        <p class="email">Company Email</p>
This should be a `label` and should be linked to your `input`

2023-09-08 16:24 UTC, shawnkost commented on css-brochure-form/index.html
> +        <p class="name">Name</p>
This should be a `label` and should be linked to your `input`

2023-09-08 16:24 UTC, shawnkost commented on css-brochure-form/index.html
> +        <p class="hiring-location">Where are you hiring?</p>
This should be a `label` and should be linked to your `input`

2023-09-08 16:24 UTC, shawnkost commented on css-brochure-form/index.html
> +          </p>
This should be a `label` and should be linked to your `select`

2023-09-08 17:08 UTC, bugass commented
updated to be labels + block, that are for the text/select

![Screenshot 2023-09-08 at 10 07 01 AM](https://github.com/bugass/c-0823-code-solutions/assets/102183396/42a21328-3223-409b-9658-72860fec0e9a)

2023-09-11 16:05 UTC, shawnkost approved these changes
👍🏻

2023-09-11 16:06 UTC, merged