completed box model
bugass/c-0823-code-solutions pull request #35
Opened 2023-09-08 16:06 UTC by bugass

Completed.
<img width="531" alt="266095083-5d892db1-e113-4760-bf10-1520a68426ea" src="https://github.com/bugass/c-0823-code-solutions/assets/102183396/905b1987-b93d-4919-ac9f-45506e1814ec">

2023-09-08 16:21 UTC, shawnkost requested changes
Couple changes here Bug!

2023-09-08 16:21 UTC, shawnkost commented on css-box-model/styles.css
> +  margin-right: 16px;
These should be the same value

2023-09-08 16:21 UTC, shawnkost commented on css-box-model/styles.css
> +  padding-bottom: 6px;
Missing a `padding-right` & `padding-left` of `16px`

2023-09-08 16:58 UTC, bugass commented
![Screenshot 2023-09-08 at 9 57 37 AM](https://github.com/bugass/c-0823-code-solutions/assets/102183396/2a4755ed-d292-4602-8247-da6df255d8cd)
revisions completed.

2023-09-11 16:05 UTC, shawnkost approved these changes
👍🏻

2023-09-11 16:06 UTC, merged